//* CREATE Actions
export const CREATE_CLIENT_REQUEST = 'CREATE_CLIENT_REQUEST';
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS';
export const CREATE_CLIENT_FAIL = 'CREATE_CLIENT_FAIL';
//* READ Actions
export const READ_CLIENT_REQUEST = 'READ_CLIENT_REQUEST';
export const READ_CLIENT_SUCCESS = 'READ_CLIENT_SUCCESS';
export const READ_CLIENT_FAIL = 'READ_CLIENT_FAIL';
//* READ All Actions
export const READ_ALL_CLIENTS_REQUEST = 'READ_ALL_CLIENTS_REQUEST';
export const READ_ALL_CLIENTS_SUCCESS = 'READ_ALL_CLIENTS_SUCCESS';
export const READ_ALL_CLIENTS_FAIL = 'READ_ALL_CLIENTS_FAIL';
//* UPDATE Actions
export const UPDATE_CLIENT_REQUEST = 'UPDATE_CLIENT_REQUEST';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAIL = 'UPDATE_CLIENT_FAIL';
//* DELETE Actions
export const DELETE_CLIENT_REQUEST = 'DELETE_CLIENT_REQUEST';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAIL = 'DELETE_CLIENT_FAIL';
